//! This file was automatically generated by rpg-editor.
//! This module must belong to crate::client::generated.
//! Do not commit this file to Git in rpg-infrastructure.

#![allow(unused_mut)]
#![allow(unused_imports)]

use crate::{client::{component::*, scene::map::MapScene}, engine::Managers};
use glam::*;
use std::collections::HashMap;
use winit::keyboard::KeyCode;

pub mod first {
    use super::*;
    pub fn init(mngrs: &mut Managers) -> MapScene {
        let _ = mngrs.gr_mngr.load_image(&mut mngrs.rs_mngr, "tiles.png");
        let mut tiles = Vec::new();
        let mut row = Vec::new();
        row.push(MapTile::new(0, 0, "tiles.png", Vec4::new(0.0, 0.0, 0.375, 0.375), true));
        tiles.push(row);
        let tiles = MapTiles { tiles };
        let mut actors = HashMap::new();
        let mut events = Vec::<Event>::new();
        MapScene::new(tiles, actors, events)
    }
}
