name: Build Check

on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libgtk-3-dev libsoup-3.0-dev librsvg2-dev libjavascriptcoregtk-4.1 webkit2gtk-4.1

      - name: Install dependencies
        run: |
          bun install
      
      - name: Check format
        run: |
          bun run format --check
          cd src-tauri
          cargo fmt --check
          cd ..

      - name: Build Tauri
        run: |
          bun tauri build
